name: my first github action
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17.3.0"
      - name: "Build Project"
        run: npm run build
      - name: "Install Node Modules"
        run: npm install
      - name: Setup finished    
        run: echo "Sucessfully Done"
